version: "3.8"

services:
  backend:
    build: ./backend
    container_name: adaptive-quiz-backend
    environment:
      - FLASK_APP=backend.app
      - SECRET_KEY=change-me-in-production
      - JWT_SECRET_KEY=change-me-jwt-prod
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app/uploads
      - backend-db:/app

  frontend:
    build: ./frontend
    container_name: adaptive-quiz-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend-data:
  backend-db:
